apiVersion: v1
kind: Pod
metadata:
  name: ricsim
  labels:
    app: ricsim
  namespace: ricsim
spec:
  containers:
    - name: ricsim
      env:
      - name: E2SIM_DIR
        value: "/playpen/previous" 
      image: quay.io/skonish/ran_sim 
      command: ["/bin/sh"]
      args: ["-c", "export E2SIM_DIR=/playpen/previous;yum install -y net-tools iputils;while true; do sleep 30; done;"]
      
